import { describe, expect, it } from 'vitest'
import { mobilityMovements, mobilityRoutines, getMobilityMovement, getMobilityRoutine } from '../data/mobility'
import { mobilityMovementIds, mobilityRoutineIds } from '../types/mobility'
import type { HistoryEntry } from '../types/history'
import { regionIds } from '../types/stretch'
import { createMobilitySession, currentMobilityStep, mobilityCompletedCount, mobilityMovedRegions, mobilityPrescriptionText, mobilityReducer, restoreMobilitySession, validMobilityPrescription, validMobilitySession } from './mobility'
import type { MobilitySessionState } from './mobility'
import { historicalMobilitySession, isFlexibilityHistory, isMobilityHistory, mobilityHistoryTotals, mobilityMovedRegionsFromHistory, mobilityToday, validMobilityHistory } from './mobilityHistory'
import { activeSessionRepository, activitySessionRepository, historyRepository, profileRepository, resetAllData, storageKeys } from './storage'
import type { StoragePort } from './storage'
import { createProgramSession, createSession, sessionReducer } from './session'
import { defaultProfile } from './profile'
import { historicalSession, historyTotals, todayCoveredRegions } from './history'
import { defaultSchedule, getScheduledProgramForDate, isScheduledProgramCompleted } from './schedule'
import { startRequiresResolution } from './sessionLaunch'

const start = new Date(2026, 8, 29, 9, 0, 0).getTime()
const memoryStorage = (): StoragePort => {
  const data = new Map<string, string>()
  return { getItem: key => data.get(key) ?? null, setItem: (key, value) => { data.set(key, value) }, removeItem: key => { data.delete(key) } }
}
function finishRoutine(id: typeof mobilityRoutineIds[number], at = start): MobilitySessionState {
  let state = createMobilitySession(id, at, `finished-${id}`)
  let now = at
  while (state.phase !== 'complete') {
    if (state.phase === 'ready') {
      const prescription = currentMobilityStep(state).prescription
      if (prescription.kind === 'seconds') { state = mobilityReducer(state, { type: 'START', now }); now += prescription.seconds * 1000; state = mobilityReducer(state, { type: 'TICK', now }) }
      else { now += 12000; state = mobilityReducer(state, { type: 'DONE', now }) }
    } else { now += 2000; state = mobilityReducer(state, { type: 'NEXT', now }) }
  }
  return state
}
const timed = () => createMobilitySession('full-body-warmup', start, 'timed')
const marchDone = () => mobilityReducer(mobilityReducer(timed(), { type: 'START', now: start }), { type: 'TICK', now: start + 45000 })

describe('curated mobility library and routines', () => {
  it('has twelve unique, stable movement IDs', () => { expect(mobilityMovements.map(item => item.id)).toEqual([...mobilityMovementIds]); expect(new Set(mobilityMovementIds).size).toBe(12) })
  it('has three unique, stable routine IDs', () => { expect(mobilityRoutines.map(item => item.id)).toEqual([...mobilityRoutineIds]); expect(new Set(mobilityRoutineIds).size).toBe(3) })
  it('references only known movements', () => { for (const routine of mobilityRoutines) for (const step of routine.steps) expect(getMobilityMovement(step.movementId).id).toBe(step.movementId) })
  it('does not duplicate movements within a routine', () => { for (const routine of mobilityRoutines) expect(new Set(routine.steps.map(step => step.movementId)).size).toBe(routine.steps.length) })
  it('has eight full-body movements', () => expect(getMobilityRoutine('full-body-warmup').steps).toHaveLength(8))
  it('has five upper-body movements', () => expect(getMobilityRoutine('upper-body-warmup').steps).toHaveLength(5))
  it('has seven lower-body movements', () => expect(getMobilityRoutine('lower-body-warmup').steps).toHaveLength(7))
  it('starts each routine with gentle marching', () => { for (const routine of mobilityRoutines) expect(routine.steps[0].movementId).toBe('march-in-place') })
  it('keeps all default full-body work standing', () => expect(getMobilityRoutine('full-body-warmup').steps.every(step => getMobilityMovement(step.movementId).position === 'standing')).toBe(true))
  it('keeps the intended full-body order', () => expect(getMobilityRoutine('full-body-warmup').steps.map(step => step.movementId)).toEqual(['march-in-place', 'arm-circles', 'standing-torso-rotation', 'bodyweight-squat', 'hip-hinge-reach', 'reverse-lunge-with-reach', 'front-to-back-leg-swing', 'ankle-rock']))
  it('uses 30 seconds of marching in upper body only', () => { expect(getMobilityRoutine('upper-body-warmup').steps[0].prescription).toEqual({ kind: 'seconds', seconds: 30 }); expect(getMobilityMovement('march-in-place').prescription).toEqual({ kind: 'seconds', seconds: 45 }) })
  it('validates timed prescriptions and rejects invalid durations', () => { expect(validMobilityPrescription({ kind: 'seconds', seconds: 45 })).toBe(true); expect(validMobilityPrescription({ kind: 'seconds', seconds: 0 })).toBe(false); expect(validMobilityPrescription({ kind: 'seconds', seconds: -1 })).toBe(false) })
  it('validates rep prescriptions', () => { expect(validMobilityPrescription({ kind: 'reps', reps: 10, perSide: false })).toBe(true); expect(validMobilityPrescription({ kind: 'reps', reps: 0, perSide: false })).toBe(false) })
  it('validates per-side prescriptions', () => { expect(validMobilityPrescription({ kind: 'reps', reps: 8, perSide: true })).toBe(true); expect(mobilityPrescriptionText(getMobilityMovement('front-to-back-leg-swing').prescription)).toBe('8 per side') })
  it('validates directional totals and copy', () => { const value = getMobilityMovement('arm-circles').prescription; expect(validMobilityPrescription(value)).toBe(true); expect(mobilityPrescriptionText(value)).toBe('10 forward · 10 backward'); expect(validMobilityPrescription({ kind: 'reps', reps: 21, perSide: false, directions: [{ label: 'Forward', reps: 10 }, { label: 'Backward', reps: 10 }] })).toBe(false) })
  it('uses valid anatomy regions for every movement', () => { for (const move of mobilityMovements) for (const id of [...move.primaryRegions, ...(move.secondaryRegions ?? [])]) expect(regionIds).toContain(id) })
  it('needs no training equipment; a wall can be optional or environmental', () => { for (const move of mobilityMovements) expect(move.equipment.every(item => /wall|floor/i.test(item))).toBe(true) })
})

describe('distinct mobility session reducer', () => {
  it('captures routine ID, ordered steps, prescriptions and start time', () => { const state = createMobilitySession('upper-body-warmup', start, 'fixed'); expect(state).toMatchObject({ kind: 'mobility', id: 'fixed', routineId: 'upper-body-warmup', movementIndex: 0, phase: 'ready', remainingMs: 30000 }); expect(state.steps).toHaveLength(5); expect(state.startedAt).toBe(new Date(start).toISOString()) })
  it('captures prescriptions independently of later library edits', () => { const state = timed(); const copied = structuredClone(state); copied.steps[0].prescription = { kind: 'seconds', seconds: 20 }; expect(state.steps[0].prescription).toEqual({ kind: 'seconds', seconds: 45 }) })
  it('uses a timestamp deadline for timed movement', () => { const state = mobilityReducer(timed(), { type: 'START', now: start }); expect(state.deadline).toBe(start + 45000); expect(state.phase).toBe('running') })
  it('shows timestamp-based remaining time', () => { const state = mobilityReducer(mobilityReducer(timed(), { type: 'START', now: start }), { type: 'TICK', now: start + 14000 }); expect(state.remainingMs).toBe(31000) })
  it('never goes below zero after a late tick', () => { const state = mobilityReducer(mobilityReducer(timed(), { type: 'START', now: start }), { type: 'TICK', now: start + 60000 }); expect(state.remainingMs).toBe(0); expect(state.phase).toBe('movement-complete') })
  it('does not count paused time after resume', () => { let state = mobilityReducer(timed(), { type: 'START', now: start }); state = mobilityReducer(state, { type: 'PAUSE', now: start + 10000 }); expect(state.remainingMs).toBe(35000); state = mobilityReducer(state, { type: 'RESUME', now: start + 70000 }); expect(state.deadline).toBe(start + 105000); state = mobilityReducer(state, { type: 'TICK', now: start + 80000 }); expect(state.remainingMs).toBe(25000) })
  it('restores an expired timer to movement complete', () => { const state = restoreMobilitySession(mobilityReducer(timed(), { type: 'START', now: start }), start + 90000); expect(state.phase).toBe('movement-complete'); expect(state.results[0]).toMatchObject({ status: 'completed', actualTimedMs: 45000 }) })
  it('never automatically starts the next movement', () => { const state = restoreMobilitySession(mobilityReducer(timed(), { type: 'START', now: start }), start + 90000); expect(state.movementIndex).toBe(0); expect(state.results).toHaveLength(1); expect(state.deadline).toBeNull() })
  it('needs explicit NEXT after time expires', () => { const state = mobilityReducer(marchDone(), { type: 'NEXT', now: start + 46000 }); expect(state.movementIndex).toBe(1); expect(state.phase).toBe('ready') })
  it('manually completes a rep movement', () => { const state = mobilityReducer(marchDone(), { type: 'NEXT', now: start + 46000 }); const done = mobilityReducer(state, { type: 'DONE', now: start + 61000 }); expect(done.results[1]).toMatchObject({ status: 'completed', actualTimedMs: null }); expect(done.phase).toBe('movement-complete') })
  it('does not auto-count repetitions before DONE', () => { const state = mobilityReducer(marchDone(), { type: 'NEXT', now: start + 46000 }); expect(mobilityReducer(state, { type: 'TICK', now: start + 500000 })).toEqual(state) })
  it('completes a per-side movement with one explicit action', () => { let state = createMobilitySession('lower-body-warmup', start); state = { ...state, movementIndex: 4, phase: 'ready', results: state.steps.slice(0, 4).map(step => ({ ...step, status: 'completed' as const, actualTimedMs: step.prescription.kind === 'seconds' ? step.prescription.seconds * 1000 : null })), remainingMs: 0 }; const done = mobilityReducer(state, { type: 'DONE', now: start + 100000 }); expect(done.results.at(-1)?.prescription).toMatchObject({ kind: 'reps', reps: 8, perSide: true }); expect(done.results.at(-1)?.status).toBe('completed') })
  it('treats both circle directions as one movement result', () => { const step = mobilityReducer(marchDone(), { type: 'NEXT', now: start + 46000 }); const done = mobilityReducer(step, { type: 'DONE', now: start + 60000 }); expect(done.results).toHaveLength(2); expect(done.results[1].prescription).toMatchObject({ reps: 20, perSide: false }) })
  it('records a skipped rep movement separately', () => { const state = mobilityReducer(mobilityReducer(marchDone(), { type: 'NEXT', now: start + 46000 }), { type: 'SKIP', now: start + 46000 }); expect(state.results[1].status).toBe('skipped'); expect(mobilityCompletedCount(state)).toBe(1) })
  it('records elapsed time when a timed movement is skipped', () => { const running = mobilityReducer(timed(), { type: 'START', now: start }); const state = mobilityReducer(running, { type: 'SKIP', now: start + 10000 }); expect(state.results[0]).toMatchObject({ status: 'skipped', actualTimedMs: 10000 }) })
  it('records actual time on early completion', () => { const running = mobilityReducer(timed(), { type: 'START', now: start }); const state = mobilityReducer(running, { type: 'COMPLETE_EARLY', now: start + 22000 }); expect(state.results[0]).toMatchObject({ status: 'completed', actualTimedMs: 22000 }) })
  it('captures timed movement duration on normal completion', () => expect(marchDone().results[0].actualTimedMs).toBe(45000))
  it('explicitly finishes a partial routine with skipped remainder', () => { const state = mobilityReducer(marchDone(), { type: 'FINISH_EARLY', now: start + 46000 }); expect(state.phase).toBe('complete'); expect(state.results).toHaveLength(8); expect(mobilityCompletedCount(state)).toBe(1); expect(state.results.slice(1).every(item => item.status === 'skipped')).toBe(true) })
  it('finishes all three routines without a static hold', () => { for (const id of mobilityRoutineIds) { const state = finishRoutine(id); expect(state.phase).toBe('complete'); expect(mobilityCompletedCount(state)).toBe(getMobilityRoutine(id).steps.length) } })
  it('marks only successful primary regions moved', () => { const state = mobilityReducer(mobilityReducer(marchDone(), { type: 'NEXT', now: start + 46000 }), { type: 'SKIP', now: start + 47000 }); expect(mobilityMovedRegions(state.results)).toEqual(new Set(['hip-flexors', 'quadriceps', 'calves'])) })
})

describe('persistence, history and flexibility isolation', () => {
  it('stores routine identity and a prescription snapshot in history', () => { const entry = historicalMobilitySession(finishRoutine('upper-body-warmup'))!; expect(entry).toMatchObject({ activityType: 'mobility', routineId: 'upper-body-warmup' }); expect(entry.movements[0].prescription).toEqual({ kind: 'seconds', seconds: 30 }); expect(validMobilityHistory(entry)).toBe(true) })
  it('stores actual session duration and only timed movement milliseconds', () => { const entry = historicalMobilitySession(finishRoutine('full-body-warmup'))!; expect(entry.durationSeconds).toBeGreaterThan(45); expect(entry.movements[0].actualTimedMs).toBe(45000); expect(entry.movements[1].actualTimedMs).toBeNull() })
  it('stores an explicitly finished partial routine with accurate skipped states', () => { const entry = historicalMobilitySession(mobilityReducer(marchDone(), { type: 'FINISH_EARLY', now: start + 46000 }))!; expect(entry.movements.filter(item => item.status === 'skipped')).toHaveLength(7); expect(validMobilityHistory(entry)).toBe(true) })
  it('rejects mobility history with a false routine identity', () => { const entry = historicalMobilitySession(finishRoutine('upper-body-warmup'))!; expect(validMobilityHistory({ ...entry, routineId: 'lower-body-warmup' })).toBe(false) })
  it('rejects rep results with fabricated timed duration', () => { const entry = historicalMobilitySession(finishRoutine('upper-body-warmup'))!; entry.movements[1].actualTimedMs = 1000; expect(validMobilityHistory(entry)).toBe(false) })
  it('loads schema 2 flexibility history without rewriting bytes', () => { const port = memoryStorage(); const staticState = sessionReducer(createProgramSession('quick-5', { holdSeconds: 20, sets: 1 }, start), { type: 'FINISH_EARLY', now: start + 1000 }); const record = historicalSession(staticState)!; const { activityType: _, ...legacy } = record; const raw = JSON.stringify({ schemaVersion: 2, data: [legacy] }); port.setItem(storageKeys.history, raw); const entries = historyRepository(port).load().value; expect(entries[0].activityType).toBe('flexibility'); expect(port.getItem(storageKeys.history)).toBe(raw) })
  it('saves flexibility and mobility in the same discriminated history', () => { const port = memoryStorage(); const repo = historyRepository(port); const staticState = sessionReducer(createSession(['cross-body-shoulder-stretch'], 'targeted', undefined, start), { type: 'FINISH_EARLY', now: start + 1000 }); repo.finish(staticState); repo.finishMobility(finishRoutine('upper-body-warmup')); const entries = historyRepository(port).load().value; expect(entries).toHaveLength(2); expect(entries.filter(isFlexibilityHistory)).toHaveLength(1); expect(entries.filter(isMobilityHistory)).toHaveLength(1); expect(JSON.parse(port.getItem(storageKeys.history)!).schemaVersion).toBe(3) })
  it('restores a saved mobility timer and captured step', () => { const port = memoryStorage(); const running = mobilityReducer(timed(), { type: 'START', now: start }); activitySessionRepository(port).save(running); const restored = activitySessionRepository(port).load().value!; expect(restored.kind).toBe('mobility'); if (restored.kind !== 'mobility') throw new Error('wrong activity'); expect(restoreMobilitySession(restored, start + 10000).remainingMs).toBe(35000); expect(restored.steps).toEqual(running.steps) })
  it('restores a Phase 3 active flexibility session from the shared slot', () => { const port = memoryStorage(); const state = createProgramSession('daily-10', { holdSeconds: 30, sets: 2 }, start); activeSessionRepository(port).save(state); const restored = activitySessionRepository(port).load().value; expect(restored).toEqual(state) })
  it('normalizes Phase 2 active static sessions without a load write', () => { const port = memoryStorage(); const state = createSession(['supine-hamstring-stretch'], 'targeted', undefined, start); const { holds: _, programId: __, ...legacy } = state; const raw = JSON.stringify({ schemaVersion: 1, data: legacy }); port.setItem(storageKeys.active, raw); expect(activitySessionRepository(port).load().value?.kind).toBe('targeted'); expect(port.getItem(storageKeys.active)).toBe(raw) })
  it('keeps one active slot when replacing flexibility with mobility', () => { const port = memoryStorage(); const repo = activitySessionRepository(port); repo.save(createProgramSession('daily-10', { holdSeconds: 30, sets: 2 }, start)); expect(startRequiresResolution(repo.load().value)).toBe(true); repo.save(timed()); expect(repo.load().value?.kind).toBe('mobility') })
  it('detects the opposite mobility-to-flexibility conflict', () => { const port = memoryStorage(); const repo = activitySessionRepository(port); repo.save(timed()); expect(startRequiresResolution(repo.load().value)).toBe(true); repo.save(createProgramSession('quick-5', { holdSeconds: 30, sets: 2 }, start)); expect(repo.load().value?.kind).toBe('program') })
  it('does not block starting after a complete session', () => expect(startRequiresResolution(finishRoutine('upper-body-warmup'))).toBe(false))
  it('does not satisfy scheduled Daily 10 after finishing mobility', () => { const schedule = defaultSchedule(); const today = new Date(2026, 8, 29, 10, 0); const mobility = historicalMobilitySession(finishRoutine('full-body-warmup'))!; expect(getScheduledProgramForDate(schedule, today)).toBe('daily-10'); expect(isScheduledProgramCompleted([], 'daily-10', today)).toBe(false); expect(mobility.activityType).toBe('mobility') })
  it("does not color static today's body after mobility only", () => { const entry = historicalMobilitySession(finishRoutine('full-body-warmup'))!; const entries: HistoryEntry[] = [entry]; expect(todayCoveredRegions(entries.filter(isFlexibilityHistory), new Date(start))).toEqual(new Set()) })
  it('does not add mobility duration to static hold time', () => { const entry = historicalMobilitySession(finishRoutine('full-body-warmup'))!; const entries: HistoryEntry[] = [entry]; expect(historyTotals(entries.filter(isFlexibilityHistory)).holdSeconds).toBe(0); expect(entry.durationSeconds).toBeGreaterThan(0) })
  it('does not count static sessions as mobility metrics', () => { const record = historicalSession(sessionReducer(createProgramSession('quick-5', { holdSeconds: 20, sets: 1 }, start), { type: 'FINISH_EARLY', now: start + 1000 }))!; const entries: HistoryEntry[] = [record]; expect(mobilityHistoryTotals(entries.filter(isMobilityHistory)).sessions).toBe(0) })
  it('does not change subjective baseline when mobility history saves', () => { const port = memoryStorage(); const before = defaultProfile(); profileRepository(port).save(before); historyRepository(port).finishMobility(finishRoutine('upper-body-warmup')); expect(profileRepository(port).load().value).toEqual(before) })
  it('filters the two activities without conflating their records', () => { const port = memoryStorage(); const repo = historyRepository(port); repo.finishMobility(finishRoutine('upper-body-warmup')); repo.finish(sessionReducer(createProgramSession('quick-5', { holdSeconds: 20, sets: 1 }, start), { type: 'FINISH_EARLY', now: start + 1000 })); expect(repo.load().value.filter(isMobilityHistory).map(item => item.routineId)).toEqual(['upper-body-warmup']); expect(repo.load().value.filter(isFlexibilityHistory).map(item => item.programId)).toEqual(['quick-5']) })
  it('counts same-day mobility separately', () => { const entry = historicalMobilitySession(finishRoutine('upper-body-warmup'))!; expect(mobilityToday([entry], new Date(start))).toHaveLength(1); expect(mobilityHistoryTotals([entry])).toMatchObject({ sessions: 1, completed: 5, prescribed: 5, days: 1 }) })
  it('uses completed movements only for mobility moved regions', () => { const entry = historicalMobilitySession(mobilityReducer(marchDone(), { type: 'FINISH_EARLY', now: start + 46000 }))!; expect(mobilityMovedRegionsFromHistory(entry)).toEqual(new Set(['hip-flexors', 'quadriceps', 'calves'])) })
  it('resets mobility and flexibility together through existing keys', () => { const port = memoryStorage(); historyRepository(port).finishMobility(finishRoutine('full-body-warmup')); activitySessionRepository(port).save(timed()); profileRepository(port).save(defaultProfile()); expect(resetAllData(port).ok).toBe(true); for (const key of Object.values(storageKeys)) expect(port.getItem(key)).toBeNull() })
  it('protects a newer active/history envelope', () => { const port = memoryStorage(); const raw = JSON.stringify({ schemaVersion: 4, data: [] }); port.setItem(storageKeys.history, raw); const repo = historyRepository(port); expect(repo.load().issue).toBeTruthy(); expect(repo.finishMobility(finishRoutine('upper-body-warmup')).ok).toBe(false); expect(port.getItem(storageKeys.history)).toBe(raw) })
  it('rejects invalid restored movement identity', () => { const state = timed(); state.steps[0].movementId = 'arm-circles'; expect(validMobilitySession(state)).toBe(false) })
  it('rejects a second completed result at the current index', () => { const state = marchDone(); state.results.push(state.results[0]); expect(validMobilitySession(state)).toBe(false) })
  it('accepts a valid completed mobility snapshot', () => expect(validMobilitySession(finishRoutine('lower-body-warmup'))).toBe(true))
})
